# Generated by Django 4.0.3 on 2022-04-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_subcategory_product_category_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default=' ', upload_to='shop/images'),
        ),
    ]
